In [4]:
import numpy as np
# Will create an array start from 0 upto 5. Last Digit is Exclusive in Python
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
a2 = np.arange(1,8)
a2

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
a3 = np.array([1,3,4,5,6,7])
a3

array([1, 3, 4, 5, 6, 7])

In [9]:
# We can also find the type and size of an array
type(a3)

numpy.ndarray

In [11]:
a3.shape

(6,)

In [12]:
a3.size

6

In [16]:
# We can also print the element in array by just giving index of the elements
a3[0:3]

array([1, 3, 4])

In [19]:
# Converting one dimensional array to 2 dimensional array
a4 = a3[np.newaxis, :]
a4

array([[1, 3, 4, 5, 6, 7]])

In [21]:
a5 = a3[:, np.newaxis]
a5

array([[1],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [22]:
# Two Dimensional Arrays are here
b= np.array([[1,2,3,4],
             [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
#Type of this array
type(b)

numpy.ndarray

In [25]:
# length of array
len(b)

2

In [27]:
# Size of an array
a.size

6

In [32]:
# array of zero
b= np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
# if you want to remove . from the value then put dtype also
b= np.zeros(10, dtype= int)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
# an array of one
c= np.ones(6, dtype = int)
c

array([1, 1, 1, 1, 1, 1])

In [38]:
c= np.empty(6)
c

array([0., 0., 0., 0., 0., 0.])

In [39]:
# Making & reshaping a 3d array
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])